sudo: required
services:
  - docker

before_install:
  - docker build -t novitsky/docker-react -f Dockerfile.dev .

script:
  - docker run novitsky/docker-react npm run test -- --coverage --watchAll=false