FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# В теории уже необязателен поскольку докер композе настроен следить за файлами, но может пригодится на случай отказа от докер-композа или еще каких причин
COPY . . 

CMD ["npm", "run", "start"]
